// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int nTimes = Integer.parseInt(args[0]);
		int heads = 0;
		int tails = 0;
		// repeats the experiment T times
		for (int t = 0; t < nTimes; t++) {
			// runs one experiment
			if (Math.random() < 0.5) { heads++; }
			else tails++;
		}
		System.out.println("> 0.5:   " + heads + " times");
		System.out.println("<= 0.5:  " + tails + " times");
		if (tails == 0) { System.out.println("CANNOT CALCULATE DIVISION OF ZERO"); }
		else { double ratio = (double) heads / tails;
			System.out.println("Ratio:   " + ratio); 
		}
	}
}
